import { Icon } from '../components/Icon';
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { useDemoStore } from '../features/admin/store';
import { dayVN, dateVN, inventory, money, revenue, staffView } from '../features/admin/domain';
import type { Action, Actor } from '../features/admin/domain';
import { Badge, Modal, Search, Select, Table } from '../features/admin/ui';
import EditDialog from '../features/admin/EditDialog';
import type { Editor } from '../features/admin/EditDialog';
import './AdminPage.css';
const nav = [['overview', 'Tổng quan', 'dashboard'], ['machines', 'Máy bán hàng', 'machine'], ['products', 'Sản phẩm & giá', 'fruit'], ['inventory', 'Tồn kho', 'inventory'], ['transactions', 'Giao dịch', 'transactions'], ['tasks', 'Công việc', 'tasks'], ['staff', 'Nhân viên', 'users']] as const;
export default function AdminPage() {
    const { data: s, error, commit, reset } = useDemoStore();
    const [path, setPath] = useState(location.pathname.replace(/\/+$/, '') || '/'), [mobile, setMobile] = useState(false), [editor, setEditor] = useState<Editor | null>(null), [resetting, setResetting] = useState(false), [notice, setNotice] = useState('');
    const [q, setQ] = useState(''), [filter, setFilter] = useState(''), [mid, setMid] = useState(''), [mode, setMode] = useState('day'), [period, setPeriod] = useState(dayVN()), [showData, setShowData] = useState(false), [expanded, setExpanded] = useState(''), [locationFilter, setLocationFilter] = useState('');
    const [staffId, setStaffId] = useState(new URLSearchParams(location.search).get('staff') || 's1');
    const isStaff = path === '/staff', screen = path.split('/')[2] || 'overview', detailId = screen === 'machines' ? path.split('/')[3] : undefined;
    useEffect(() => { const pop = () => { setPath(location.pathname.replace(/\/+$/, '') || '/'); setQ(''); setFilter(''); setMid(''); }; addEventListener('popstate', pop); return () => removeEventListener('popstate', pop); }, []);
    useEffect(() => {
        if (!mobile) return;
        document.querySelector<HTMLButtonElement>('.a-sidebar nav button')?.focus();
        const closeMenu = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMobile(false); requestAnimationFrame(() => document.querySelector<HTMLButtonElement>('.a-menu')?.focus()); } };
        const resize = () => { if (window.innerWidth > 960) setMobile(false); };
        addEventListener('keydown', closeMenu); addEventListener('resize', resize);
        return () => { removeEventListener('keydown', closeMenu); removeEventListener('resize', resize); };
    }, [mobile]);
    function go(screen: string, f = '') { const next = screen.startsWith('/') ? screen : `/admin/${screen === 'overview' ? '' : screen}`; history.pushState({}, '', next); setPath(next.split('?')[0]); setQ(''); setFilter(f); setMid(''); setLocationFilter(''); setMobile(false); setExpanded(''); setNotice(''); window.scrollTo(0, 0); }
    function run(a: Action, actor?: Actor) { commit(a, actor); setNotice('Đã lưu thay đổi vào dữ liệu mẫu.'); }
    const machines = s.machines.filter(m => !m.archived), products = s.products.filter(p => !p.archived), machineName = (id: string) => s.machines.find(m => m.id === id)?.code || 'Máy đã ngừng', productName = (id: string) => s.products.find(p => p.id === id)?.name || 'Sản phẩm đã ngừng';
    const matches = (...parts: unknown[]) => parts.join(' ').toLocaleLowerCase('vi').includes(q.toLocaleLowerCase('vi'));
    const activeSlots = s.slots.filter(slot => machines.some(m => m.id === slot.machineId));
    const stats = revenue(s.transactions, mode, period, mid), today = dayVN(), view = staffView(s, staffId);
    const machineItems = machines.map(m => ({ id: m.id, name: `${m.code} · ${m.location}` }));
    const periodControls = <div className="a-period"><div className="a-segment" aria-label="Khoảng thời gian">{[['day', 'Hôm nay'], ['month', 'Theo tháng'], ['year', 'Theo năm']].map(([v, l]) => <button key={v} aria-pressed={mode === v} onClick={() => { setMode(v); setPeriod(v === 'day' ? today : v === 'month' ? today.slice(0, 7) : today.slice(0, 4)); }}>{l}</button>)}</div>{mode !== 'day' && <input aria-label={mode === 'month' ? 'Tháng thống kê' : 'Năm thống kê'} type={mode === 'month' ? 'month' : 'number'} min={mode === 'year' ? '2000' : undefined} max={mode === 'year' ? '2100' : undefined} value={period} onInput={e => { if(e.currentTarget.value) setPeriod(e.currentTarget.value); }} onChange={e => { if (e.target.value)
        setPeriod(e.target.value); }}/>}<Select label="Phạm vi máy" value={mid} onChange={setMid} items={machineItems} empty="Tất cả máy"/></div>;
    const transactionTable = (items: typeof s.transactions) => <Table heads={['Mã đơn / thời gian', 'Máy / vị trí', 'Sản phẩm', 'Số tiền', 'Trạng thái', 'Thao tác']} rows={items.map(t => ({ id: t.id, cells: [<><strong>{t.id}</strong><small>{dateVN(t.at)}</small></>, <>{t.machineCode}<small>{t.location}</small></>, t.product, money(t.amount), <><Badge value={t.status}/>{t.paid && t.status === 'DISPENSE_FAILED' && <Badge value={t.incident}/>}</>, <div className="a-actions" key="cell-5"><button onClick={() => setEditor({ kind: 'transaction', id: t.id })}>Chi tiết</button>{t.paid && t.status === 'DISPENSE_FAILED' && !['RESOLVED', 'REFUNDED'].includes(t.incident) && <button onClick={() => setEditor({ kind: 'incident', id: t.id })}>Xử lý</button>}</div>] }))}/>;
    function taskTable(tasks: typeof s.tasks, staffMode = false) { return <Table heads={['Công việc', 'Máy', 'Nhân viên / hạn', 'Trạng thái', 'Thao tác']} rows={tasks.map(t => ({ id: t.id, cells: [<><Badge value={t.kind}/><strong>{t.description}</strong></>, machineName(t.machineId), <>{s.staff.find(x => x.id === t.staffId)?.name}<small className={t.due < today && !['DONE', 'CANCELLED'].includes(t.status) ? 'a-danger' : ''}>{t.due}{t.due < today && !['DONE', 'CANCELLED'].includes(t.status) ? ' · Quá hạn' : ''}</small></>, <Badge value={t.status} key="cell-3"/>, <div className="a-actions" key="cell-4"><button onClick={() => setEditor({ kind: 'detail', id: t.id })}>Chi tiết</button>{!staffMode && t.status === 'ASSIGNED' && <button onClick={() => setEditor({ kind: 'task', id: t.id })}>Sửa</button>}{!['DONE', 'CANCELLED'].includes(t.status) && (staffMode ? <>{t.status === 'ASSIGNED' ? <button onClick={() => { try {
                run({ type: 'task-status', id: t.id, status: 'IN_PROGRESS', note: '' }, { role: 'STAFF', id: staffId });
            }
            catch (e) {
                setNotice(String(e));
            } }}>Bắt đầu</button> : <button className="a-primary" onClick={() => setEditor({ kind: 'complete', id: t.id, staffId })}>Hoàn thành</button>}<button onClick={() => setEditor({ kind: 'help', id: t.id, staffId })}>Cần hỗ trợ</button></> : <button onClick={() => setEditor({ kind: 'cancel', id: t.id })}>Hủy</button>)}</div>] }))}/>; }
    function stockTable(machineId = '') { return <Table heads={['Máy / ngăn', 'Sản phẩm', 'Có thể bán / sức chứa', 'Cảnh báo', 'Thao tác']} rows={activeSlots.filter(slot => (!machineId || slot.machineId === machineId) && (!mid || slot.machineId === mid) && matches(machineName(slot.machineId), slot.code, productName(slot.productId))).filter(slot => { const i = inventory(s, slot.id); return !filter || filter === 'low' && i.low || filter === 'expiring' && i.expiring || filter === 'expired' && i.expired; }).map(slot => { const i = inventory(s, slot.id); return { id: slot.id, cells: [<>{machineName(slot.machineId)}<small>Ngăn {slot.code}</small></>, productName(slot.productId), <><strong>{i.sellable} / {slot.capacity} hộp</strong><progress aria-label={`Sức chứa ngăn ${slot.code}`} value={i.total} max={slot.capacity}/><small>Thực có {i.total} hộp, gồm hàng hết hạn</small></>, <>{i.low && <Badge value="Sắp hết hàng"/>}{i.expiring && <Badge value="Sắp hết hạn"/>}{i.expired && <Badge value="Đã hết hạn"/>}{!i.low && !i.expiring && !i.expired && <Badge value="Bình thường"/>}</>, <div className="a-actions" key="cell-4"><button onClick={() => setExpanded(expanded === slot.id ? '' : slot.id)}>Xem lô</button><button onClick={() => setEditor({ kind: 'slot', id: slot.id })}>Sửa ngăn</button><button onClick={() => setEditor({ kind: 'task', machineId: slot.machineId })}>Giao refill</button></div>] }; })}/>; }
    const lotsPanel = expanded && <section className="a-panel"><div className="a-section-head"><h2>Các lô · ngăn {s.slots.find(x => x.id === expanded)?.code}</h2><button onClick={() => setExpanded('')}>Đóng danh sách lô</button></div><Table heads={['Mã lô', 'Số hộp', 'Hạn dùng', 'Thao tác']} rows={s.lots.filter(l => l.slotId === expanded && l.quantity > 0).map(l => ({ id: l.id, cells: [l.id, l.quantity, <span className={l.expiry < today ? 'a-danger' : ''} key="cell-2">{l.expiry}</span>, <button onClick={() => setEditor({ kind: 'remove', id: l.id })} key="cell-3">Lấy hàng ra</button>] }))}/></section>;
    let content: ReactNode;
    if (isStaff)
        content = <><div className="a-toolbar"><Select label="Xem với nhân viên mẫu" value={staffId} onChange={id => { setStaffId(id); history.replaceState({}, "", `/staff?staff=${encodeURIComponent(id)}`); }} items={s.staff.filter(x => x.active)}/><span>Chỉ công việc và máy được phân công</span></div><section className="a-panel"><h2>Máy của {view.staff?.name || 'nhân viên'}</h2><div className="a-machine-strip">{view.machines.map(m => <div key={m.id}><strong>{m.code}</strong><span>{m.location}</span><Badge value={m.status}/></div>)}</div>{!view.machines.length && <p className="a-empty">Chưa được phân công máy nào.</p>}</section><section className="a-panel"><h2>Công việc của tôi</h2>{taskTable(view.tasks, true)}</section></>;
    else if (screen === 'overview')
        content = <>{periodControls}<div className="a-metrics"><div><span>Doanh thu hợp lệ</span><strong>{money(stats.total)}</strong><small>Thanh toán & nhả hàng thành công</small></div><div><span>Giao dịch thành công</span><strong>{stats.successful}<em> đơn</em></strong><small>Trong khoảng thời gian đã chọn</small></div><div><span>Nhả hàng thất bại</span><strong>{stats.failed}<em> đơn</em></strong><small>Đã thu tiền · không tính doanh thu</small></div></div><div className="a-overview-grid"><section className="a-panel"><div className="a-section-head"><div><h2>Nhịp doanh thu</h2><p>{mode === 'day' ? 'Theo giờ hôm nay' : mode === 'month' ? `Theo ngày · ${period}` : `Theo tháng · ${period}`} · giờ Việt Nam</p></div><button onClick={() => setShowData(!showData)}>{showData ? 'Ẩn số liệu' : 'Xem số liệu'}</button></div><div className="a-chart" role="img" aria-label={`Biểu đồ doanh thu: tổng ${money(stats.total)}. Dùng nút Xem số liệu để đọc từng cột.`}>{stats.buckets.map((b, i) => <div className="a-bar-column" key={b.label} title={`${b.label}: ${money(b.amount)}`}><div className="a-bar" style={{ height: `${b.amount / Math.max(1, ...stats.buckets.map(b => b.amount)) * 100}%` }}/>{i % (mode === 'month' ? 5 : mode === 'day' ? 3 : 1) === 0 && <span>{b.label}</span>}</div>)}</div>{stats.total === 0 && <p className="a-hint">Chưa có doanh thu hợp lệ trong khoảng này.</p>}{showData && <Table heads={['Khoảng', 'Doanh thu']} rows={stats.buckets.map(b => ({ id: b.label, cells: [b.label, money(b.amount)] }))}/>}</section><section className="a-panel a-attention"><h2>Cần chú ý</h2><p>Toàn bộ hệ thống · hiện tại</p>{[[s.transactions.filter(t => t.paid && t.status === 'DISPENSE_FAILED' && !['RESOLVED', 'REFUNDED'].includes(t.incident)).length, 'Sự cố chưa giải quyết', 'transactions', 'failed'], [activeSlots.filter(x => inventory(s, x.id).low).length, 'Ngăn sắp hết hàng', 'inventory', 'low'], [activeSlots.filter(x => inventory(s, x.id).expiring).length, 'Ngăn có lô sắp hết hạn', 'inventory', 'expiring'], [s.tasks.filter(t => t.kind === 'MAINTENANCE' && t.due < today && !['DONE', 'CANCELLED'].includes(t.status)).length, 'Bảo trì quá hạn', 'tasks', 'overdue']].map(([n, l, p, f]) => <button key={String(l)} onClick={() => go(String(p), String(f))}><strong>{n}</strong><span>{l}</span><span>↗</span></button>)}<small>Sắp hết hàng: ≤ 2 hộp có thể bán.<br />Sắp hết hạn: trong hôm nay hoặc ngày mai.</small></section></div><section className="a-panel"><div className="a-section-head"><h2>Giao dịch gần đây</h2><button onClick={() => go('transactions')}>Tất cả giao dịch →</button></div>{transactionTable(stats.transactions.slice(0, 6))}</section></>;
    else if (screen === 'machines' && !detailId)
        content = <><div className="a-toolbar"><Search value={q} onChange={setQ} placeholder="Tìm mã máy, tên hoặc vị trí"/><Select label="Vận hành" value={filter} onChange={setFilter} empty="Tất cả trạng thái" items={['ACTIVE', 'MAINTENANCE', 'INACTIVE'].map(id => ({ id, name: ({ ACTIVE: 'Hoạt động', MAINTENANCE: 'Bảo trì', INACTIVE: 'Ngừng hoạt động' })[id]! }))}/><Select label="Địa điểm" value={locationFilter} onChange={setLocationFilter} empty="Tất cả địa điểm" items={[...new Set(machines.map(m => m.location))].map(id => ({ id, name: id }))}/></div><section className="a-panel">{<Table heads={['Máy', 'Vị trí', 'Vận hành', 'Kết nối mẫu', 'Thao tác']} rows={machines.filter(m => matches(m.code, m.name, m.location) && (!filter || m.status === filter) && (!locationFilter || m.location === locationFilter)).map(m => ({ id: m.id, cells: [<><strong>{m.code}</strong><small>{m.name}</small></>, m.location, <Badge value={m.status} key="cell-2"/>, <>{m.online ? '● Trực tuyến' : '○ Ngoại tuyến'}<small>{m.lastSeen ? dateVN(m.lastSeen) : 'Chưa có dữ liệu'}</small></>, <div className="a-actions" key="cell-4"><button onClick={() => go(`machines/${m.id}`)}>Mở máy</button><button onClick={() => setEditor({ kind: 'machine', id: m.id })}>Sửa</button><button onClick={() => setEditor({ kind: 'archiveMachine', id: m.id })}>Xóa</button></div>] }))}/>}</section></>;
    else if (screen === 'machines' && detailId) {
        const m = machines.find(x => x.id === detailId);
        content = m ? <><button className="a-back" onClick={() => go('machines')}>← Danh sách máy</button><section className="a-panel"><div className="a-section-head"><div><h2>{m.code} · {m.name}</h2><p>{m.location}</p></div><Badge value={m.status}/></div><div className="a-actions"><button onClick={() => setEditor({ kind: 'machine', id: m.id })}>Sửa máy</button><button onClick={() => setEditor({ kind: 'slot', machineId: m.id })}>+ Thêm ngăn</button><button onClick={() => setEditor({ kind: 'price', machineId: m.id })}>Thiết lập giá</button><button className="a-primary" onClick={() => setEditor({ kind: 'task', machineId: m.id })}>Phân công</button></div></section><section className="a-panel"><h2>Ngăn & tồn kho</h2>{stockTable(m.id)}</section>{lotsPanel}<section className="a-panel"><h2>Giá tại máy</h2><Table heads={['Sản phẩm', 'Giá bán', 'Thao tác']} rows={products.map(p => ({ id: p.id, cells: [p.name, s.prices.some(x => x.productId === p.id && x.machineId === m.id) ? money(s.prices.find(x => x.productId === p.id && x.machineId === m.id)!.amount) : 'Chưa thiết lập', <button onClick={() => setEditor({ kind: 'price', id: p.id, machineId: m.id })} key="cell-2">Sửa giá</button>] }))}/></section><section className="a-panel"><h2>Công việc tại máy</h2>{taskTable(s.tasks.filter(t => t.machineId === m.id))}</section><section className="a-panel"><h2>Lịch sử giao dịch</h2>{transactionTable(s.transactions.filter(t => t.machineId === m.id))}</section></> : <p className="a-empty">Máy không tồn tại hoặc đã ngừng sử dụng.</p>;
    }
    else if (screen === 'products')
        content = <><div className="a-toolbar"><Search value={q} onChange={setQ} placeholder="Tìm tên hoặc thông tin sản phẩm"/><button onClick={() => setEditor({ kind: 'price' })}>Thiết lập giá theo máy</button></div><section className="a-panel"><Table heads={['Sản phẩm', 'Thông tin', 'Phạm vi giá tại các máy', 'Thao tác']} rows={products.filter(p => matches(p.name, p.description)).map(p => { const prices = s.prices.filter(x => x.productId === p.id && machines.some(m => m.id === x.machineId)).map(x => x.amount); return { id: p.id, cells: [<div className="a-product" key="cell-0">{p.image ? <img src={p.image} alt=""/> : <span aria-hidden="true" className="a-fruit-mark">◒</span>}<strong>{p.name}</strong></div>, p.description, prices.length ? `${money(Math.min(...prices))} – ${money(Math.max(...prices))}` : 'Chưa thiết lập', <div className="a-actions" key="cell-3"><button onClick={() => setEditor({ kind: 'product', id: p.id })}>Sửa</button><button onClick={() => setEditor({ kind: 'price', id: p.id })}>Giá theo máy</button><button onClick={() => setEditor({ kind: 'archiveProduct', id: p.id })}>Xóa</button></div>] }; })}/></section></>;
    else if (screen === 'inventory')
        content = <><div className="a-toolbar"><Search value={q} onChange={setQ} placeholder="Tìm máy, ngăn hoặc sản phẩm"/><Select label="Máy" value={mid} onChange={setMid} items={machineItems} empty="Tất cả máy"/><Select label="Tình trạng tồn kho" value={filter} onChange={setFilter} empty="Tất cả" items={[{ id: 'low', name: 'Sắp hết hàng (≤ 2 hộp)' }, { id: 'expiring', name: 'Sắp hết hạn (≤ 1 ngày)' }, { id: 'expired', name: 'Có hàng hết hạn' }]}/></div><p className="a-hint">Mỗi ngăn chứa một sản phẩm, nhiều lô hạn dùng. Hàng hết hạn vẫn chiếm sức chứa cho đến khi được lấy ra.</p><section className="a-panel">{stockTable()}</section>{lotsPanel}</>;
    else if (screen === 'transactions')
        content = <>{filter !== 'failed' ? periodControls : <p className="a-hint">Nhả hàng thất bại · toàn bộ lịch sử, không giới hạn ngày.</p>}<div className="a-toolbar"><div className="a-segment"><button aria-pressed={filter !== 'failed'} onClick={() => setFilter('')}>Tất cả giao dịch</button><button aria-pressed={filter === 'failed'} onClick={() => setFilter('failed')}>Nhả hàng thất bại</button></div><Search value={q} onChange={setQ} placeholder="Tìm mã đơn, máy, vị trí hoặc trạng thái"/></div><section className="a-panel">{transactionTable((filter === 'failed' ? s.transactions : stats.transactions).filter(t => matches(t.id, t.machineCode, t.location, ({ WAITING: 'Chờ xử lý', PROCESSING: 'Đang xử lý', REFUNDED: 'Đã hoàn tiền', RESOLVED: 'Đã giải quyết' })[t.incident]) && (filter !== 'failed' || t.paid && t.status === 'DISPENSE_FAILED')))}</section></>;
    else if (screen === 'tasks')
        content = <><div className="a-toolbar"><Search value={q} onChange={setQ} placeholder="Tìm mô tả, máy hoặc nhân viên"/><Select label="Lọc công việc" value={filter} onChange={setFilter} empty="Tất cả công việc" items={[{ id: 'REFILL', name: 'Refill' }, { id: 'MAINTENANCE', name: 'Bảo trì' }, { id: 'overdue', name: 'Bảo trì quá hạn' }, { id: 'ASSIGNED', name: 'Đã phân công' }, { id: 'IN_PROGRESS', name: 'Đang thực hiện' }, { id: 'NEEDS_HELP', name: 'Cần hỗ trợ' }, { id: 'DONE', name: 'Hoàn thành' }, { id: 'CANCELLED', name: 'Đã hủy' }]}/></div><section className="a-panel">{taskTable(s.tasks.filter(t => matches(t.description, machineName(t.machineId), s.staff.find(x => x.id === t.staffId)?.name) && (!filter || t.kind === filter || t.status === filter || filter === 'overdue' && t.kind === 'MAINTENANCE' && t.due < today && !['DONE', 'CANCELLED'].includes(t.status))))}</section></>;
    else if (screen === 'staff')
        content = <><div className="a-toolbar"><Search value={q} onChange={setQ} placeholder="Tìm họ tên hoặc email"/></div><section className="a-panel"><Table heads={['Nhân viên', 'Máy phụ trách', 'Trạng thái', 'Thao tác']} rows={s.staff.filter(x => matches(x.name, x.email)).map(x => ({ id: x.id, cells: [<><strong>{x.name}</strong><small>{x.email}</small></>, x.machineIds.map(machineName).join(', ') || 'Chưa phân công', x.active ? 'Đang hoạt động' : 'Đã khóa', <div className="a-actions" key="cell-3"><button onClick={() => setEditor({ kind: 'staff', id: x.id })}>Sửa / khóa</button>{x.active && <button onClick={() => { setStaffId(x.id); go('/staff?staff=' + x.id); }}>Xem staff mẫu</button>}</div>] }))}/></section></>;
    else
        content = <p className="a-empty">Trang quản trị không tồn tại. <button onClick={() => go('overview')}>Về tổng quan</button></p>;
    const addKind: Record<string, string> = { machines: 'machine', products: 'product', inventory: 'slot', tasks: 'task', staff: 'staff' };
    return <div className="admin-app a-shell"><a className="a-skip" href="#admin-main">Đến nội dung</a><aside className={`a-sidebar ${mobile ? 'is-open' : ''}`}><a className="a-brand" href="/">Fruit<span>Vending</span><i>●</i></a><p className="a-workspace">Không gian quản trị</p><nav aria-label="Quản trị">{isStaff ? <button className="is-current">✓ Công việc của tôi</button> : nav.map(([key, label, icon]) => <button key={key} className={screen === key ? 'is-current' : ''} aria-current={screen === key ? 'page' : undefined} onClick={() => go(key)}><Icon name={icon}/>{label}</button>)}</nav><div className="a-sidebar-bottom"><div className="a-avatar">{isStaff ? 'S' : 'A'}</div><div><strong>{isStaff ? 'Staff mẫu' : 'Admin mẫu'}</strong><small>Fruit Vending</small></div></div><a className="a-exit" href="/login">Trang đăng nhập ↗</a></aside>{mobile && <button className="a-scrim" aria-label="Đóng điều hướng" onClick={() => setMobile(false)}/>}
 <div className="a-workarea" inert={mobile}><div className="a-demo"><span><b>Dữ liệu mẫu</b> · Lưu trên trình duyệt này, chưa kết nối máy thật.</span><div><button onClick={() => go(isStaff ? 'overview' : '/staff')}>{isStaff ? 'Về admin mẫu' : 'Xem staff mẫu'}</button><button onClick={() => setResetting(true)}>Đặt lại mẫu</button></div></div><main id="admin-main"><header className="a-page-head"><div className="a-title-group"><button className="a-menu" aria-label="Mở điều hướng" aria-expanded={mobile} onClick={() => setMobile(!mobile)}><Icon name="menu"/></button><div><p className="a-breadcrumb">Fruit Vending <span>/</span> {isStaff ? 'Nhân viên' : 'Quản trị'}</p><h1>{isStaff ? 'Công việc của tôi' : detailId ? 'Chi tiết máy' : nav.find(([key]) => key === screen)?.[1] || 'Quản trị'}</h1><p>{isStaff ? 'Nhận việc, cập nhật số lượng và hoàn thành tại máy.' : screen === 'overview' ? 'Một góc nhìn rõ ràng về hoạt động hôm nay.' : 'Quản lý hoạt động trên toàn bộ hệ thống.'}</p></div></div>{!isStaff && addKind[screen] && !detailId && <button className="a-primary" onClick={() => setEditor({ kind: addKind[screen] })}>+ {screen === 'tasks' ? 'Phân công' : screen === 'staff' ? 'Thêm nhân viên' : screen === 'inventory' ? 'Thêm ngăn' : screen === 'products' ? 'Thêm sản phẩm' : 'Thêm máy'}</button>}</header>{error && <p className="a-error" role="alert">{error}</p>}{notice && <div className="a-notice" role="status">{notice}<button aria-label="Đóng thông báo" onClick={() => setNotice('')}>×</button></div>}{content}<footer className="a-page-footer">Fruit Vending · Bản thử nghiệm quản trị <span>Múi giờ Việt Nam (UTC+7)</span></footer></main></div>
 {editor && <EditDialog key={`${editor.kind}-${editor.id || 'new'}`} editor={editor} store={s} commit={run} close={() => setEditor(null)}/>} {resetting && <Modal title="Đặt lại dữ liệu mẫu?" close={() => setResetting(false)} onSave={() => { reset(); setNotice('Đã tạo lại dữ liệu mẫu.'); }} save="Đặt lại mẫu"><p>Các máy, sản phẩm, phân công, ảnh và thay đổi mẫu đã lưu trên trình duyệt này sẽ được thay bằng bộ dữ liệu ban đầu.</p></Modal>}</div>;
}


